# Generated by Django 4.2.3 on 2023-08-01 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('service_type', models.CharField(choices=[('passport', 'passport'), ('photoshoot', 'photoshoot'), ('photo_printing', 'photo_printing')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.customer')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management_app.gallary')),
            ],
        ),
    ]
