# Generated by Django 4.2.3 on 2023-08-02 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='Service_transaction',
            new_name='ServiceTransaction',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
