# Generated by Django 4.2.3 on 2023-08-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetransaction',
            old_name='service_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.gallery'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
