# Generated by Django 4.2.3 on 2023-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_gallery_description_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'wedding'), ('family pics', 'family pics'), ('birthday', 'birthday')], max_length=100, null=True),
        ),
    ]
