# Generated by Django 4.2.3 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0007_remove_servicetransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='age',
            field=models.CharField(choices=[('below 1 year', 'below 1 year'), ('teenager', 'teenager'), ('adult', 'adult')], max_length=20, null=True),
        ),
    ]
