# Generated by Django 4.2.3 on 2023-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
