# Generated by Django 4.2.3 on 2023-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0010_analytics_date_alter_analytics_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_width',
            field=models.CharField(choices=[('large-small-height', 'large-small-height'), ('small-height', 'small-height'), ('large-height', 'large-height'), ('medium-large-height', 'medium-large-height'), ('medium-small-height', 'medium-small-height')], editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
