# Generated by Django 4.2.3 on 2023-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0011_gallery_image_width_gallery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_width',
            field=models.CharField(choices=[('large-small-height', 'large-small-height'), ('small-height', 'small-height'), ('medium-large-height', 'medium-large-height'), ('medium-small-height', 'medium-small-height'), ('large-height', 'large-height')], editable=False, max_length=20, null=True),
        ),
    ]
