# Generated by Django 4.2.3 on 2023-08-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0012_contacts_alter_customer_email_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
