# Generated by Django 4.2.3 on 2023-08-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0015_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetransaction',
            name='job_status',
            field=models.CharField(choices=[('completed', 'completed'), ('in progress', 'in progress'), ('cancelled', 'cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='type',
            field=models.CharField(choices=[('passport', 'passport'), ('Hardcopy', 'Hardcopy'), ('Softcopy', 'Softcopy'), ('photo_printing', 'photo_printing'), ('others', 'others')], max_length=20),
        ),
    ]
