# Generated by Django 4.2.3 on 2023-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0016_servicetransaction_job_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='customer_management.image'),
        ),
    ]
