# Generated by Django 4.2.3 on 2023-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0017_image_remove_gallery_images_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='age',
        ),
        migrations.AddField(
            model_name='image',
            name='age',
            field=models.CharField(choices=[('below 1 year', 'below 1 year'), ('teenager', 'teenager'), ('adult', 'adult')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
