# Generated by Django 4.2.3 on 2023-08-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0019_rename_title_image_name_remove_gallery_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'wedding'), ('lifestyle', 'birthday'), ('natural', 'family pics'), ('videos', 'others')], max_length=100, null=True),
        ),
    ]
