# Generated by Django 4.2.3 on 2023-08-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0020_remove_image_category_remove_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer'),
        ),
    ]
